[project]
name = "project-euler-solutions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[tool.uv]
dev-dependencies = [
    "mkdocs-material>=9.5.42",
]
